<?php

namespace App\Filament\Resources\MediaAssetResource\RelationManagers;

use App\Models\MediaSource;
use App\Services\MediaSourceService;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Table;

class MediaSourcesRelationManager extends RelationManager
{
    protected static string $relationship = 'sources';

    public static function getDescription(): string
    {
        $enabled = (bool) config('cdn.laravel_worker_enabled', false);
        $pullEnabled = (bool) config('cdn.laravel_worker_pull_enabled', true);
        $url = config('cdn.laravel_worker_api_url', '');
        if ($enabled && $url !== '') {
            $mode = $pullEnabled ? ' CDN pulls the HLS ZIP from the worker (pull mode).' : ' Worker pushes optimized + HLS back to CDN.';
            return 'Faststart runs on CDN; HLS is generated by the external Laravel worker.' . $mode . ' Use "Queue for optimization" or "Run re-optimise" to re-send a source.';
        }
        return 'Sources are optimized directly on the CDN (faststart + HLS) using the local optimization queue. To use the external Laravel worker, set CDN_LARAVEL_WORKER_ENABLED=true and CDN_LARAVEL_WORKER_PULL_ENABLED=true, then configure CDN_LARAVEL_WORKER_API_URL / CDN_LARAVEL_WORKER_API_TOKEN.';
    }

    public function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Select::make('source_type')
                ->required()
                ->live()
                ->afterStateUpdated(fn (Forms\Set $set) => $set('imported_source_id', null))
                ->options([
                    'url' => 'Direct URL',
                    'embed' => 'Embed',
                    'upload' => 'Local Upload',
                    'remote_fetch' => 'Remote Fetch',
                ]),
            Forms\Components\Textarea::make('source_url')
                ->label('Source URL or Embed URL')
                ->rows(3)
                ->visible(fn (Forms\Get $get): bool => in_array($get('source_type'), ['url', 'embed', 'remote_fetch'], true))
                ->required(fn (Forms\Get $get): bool => in_array($get('source_type'), ['url', 'embed', 'remote_fetch'], true))
                ->rule(fn (Forms\Get $get) => $get('source_type') === 'embed'
                    ? ['nullable', 'string']
                    : ['required', 'url']),
            Forms\Components\Hidden::make('imported_source_id')
                ->dehydrated(true),
            Forms\Components\Radio::make('import_mode')
                ->label('Remote Import Mode')
                ->default((string) config('cdn.default_import_mode', 'queue'))
                ->options([
                    'queue' => 'Queue',
                    'now' => 'Import Now',
                ])
                ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'remote_fetch')
                ->dehydrated(fn (Forms\Get $get): bool => $get('source_type') === 'remote_fetch'),
            Forms\Components\FileUpload::make('upload_file')
                ->label('Video File')
                ->disk(config('cdn.disk', 'public'))
                ->directory('media/tmp')
                ->acceptedFileTypes(['video/*'])
                ->preserveFilenames()
                ->maxSize((int) config('cdn.max_upload_mb', 2048) * 1024)
                ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'upload')
                ->required(fn (Forms\Get $get): bool => $get('source_type') === 'upload')
                ->helperText('For large files, upload may take time before import starts.'),
            Forms\Components\Actions::make([
                Forms\Components\Actions\Action::make('start_remote_import')
                    ->label('Start Import Now')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('info')
                    ->visible(fn (Forms\Get $get): bool => $get('source_type') === 'remote_fetch')
                    ->action(function (Forms\Get $get, Forms\Set $set, ?MediaSource $record): void {
                        $sourceUrl = trim((string) ($get('source_url') ?? ''));
                        $importMode = (string) ($get('import_mode') ?? config('cdn.default_import_mode', 'queue'));

                        if ($sourceUrl === '') {
                            Notification::make()
                                ->warning()
                                ->title('Source URL is required')
                                ->body('Please add a valid URL before starting import.')
                                ->send();
                            return;
                        }

                        $service = app(MediaSourceService::class);
                        $isActive = (bool) ($get('is_active') ?? true);

                        if ($record) {
                            $record->update([
                                'source_type' => 'remote_fetch',
                                'source_url' => $sourceUrl,
                                'is_active' => $isActive,
                            ]);
                            if ($importMode === 'now') {
                                $service->importRemoteNow($record);
                                $record->refresh();
                            } else {
                                $service->queueRemoteImport($record);
                            }
                            $set('imported_source_id', $record->id);

                            if ($importMode === 'now') {
                                if ($record->status === 'failed') {
                                    Notification::make()
                                        ->danger()
                                        ->title('Import failed')
                                        ->body($record->failure_reason ?: 'Remote import failed.')
                                        ->send();
                                } else {
                                    Notification::make()
                                        ->success()
                                        ->title('Import completed')
                                        ->body('Remote media was imported successfully.')
                                        ->send();
                                }
                            } else {
                                Notification::make()
                                    ->info()
                                    ->title('Import queued')
                                    ->body('Re-import queued. Progress is updating in the table.')
                                    ->send();
                            }

                            return;
                        }

                        $asset = $this->getOwnerRecord();
                        $source = MediaSource::create([
                            'media_asset_id' => $asset->id,
                            'source_type' => 'remote_fetch',
                            'source_url' => $sourceUrl,
                            'status' => 'pending',
                            'is_active' => $isActive,
                        ]);

                        if ($importMode === 'now') {
                            $service->importRemoteNow($source);
                            $source->refresh();
                        } else {
                            $service->queueRemoteImport($source);
                        }
                        $set('imported_source_id', $source->id);

                        if ($importMode === 'now') {
                            if ($source->status === 'failed') {
                                Notification::make()
                                    ->danger()
                                    ->title('Import failed')
                                    ->body($source->failure_reason ?: 'Remote import failed.')
                                    ->send();
                            } else {
                                Notification::make()
                                    ->success()
                                    ->title('Import completed')
                                    ->body('Source was created and imported immediately.')
                                    ->send();
                            }
                        } else {
                            Notification::make()
                                ->info()
                                ->title('Import queued and auto-saved')
                                ->body('Source has been created. You can close this dialog and watch progress.')
                                ->send();
                        }
                    }),
            ]),
            Forms\Components\Toggle::make('is_active')
                ->default(true),
            Forms\Components\Placeholder::make('import_progress')
                ->label('Import Progress')
                ->content(function (?MediaSource $record): string {
                    if (! $record) {
                        return 'Progress will appear after source is created.';
                    }

                    $percent = (int) ($record->progress_percent ?? 0);
                    $downloaded = $record->bytes_downloaded ? $this->formatBytes((int) $record->bytes_downloaded) : '0 B';
                    $total = $record->bytes_total ? $this->formatBytes((int) $record->bytes_total) : 'Unknown total';
                    $status = strtoupper($record->status);

                    return "{$status} - {$percent}% ({$downloaded} / {$total})";
                })
                ->visible(fn (?MediaSource $record): bool => (bool) $record),
            Forms\Components\Textarea::make('failure_reason')
                ->disabled()
                ->dehydrated(false)
                ->rows(2)
                ->visible(fn (?MediaSource $record): bool => (bool) $record?->failure_reason),
            Forms\Components\Textarea::make('last_error')
                ->disabled()
                ->dehydrated(false)
                ->rows(3)
                ->visible(fn (?MediaSource $record): bool => (bool) $record?->last_error),
        ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->description(self::getDescription())
            ->poll('2s')
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->sortable(),
                Tables\Columns\TextColumn::make('source_type')
                    ->badge(),
                Tables\Columns\TextColumn::make('status')
                    ->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'ready' => 'success',
                        'failed' => 'danger',
                        'downloading', 'processing', 'proxying', 'uploading' => 'warning',
                        default => 'info',
                    }),
                Tables\Columns\IconColumn::make('is_active')
                    ->boolean(),
                Tables\Columns\TextColumn::make('mime_type')
                    ->toggleable(),
                Tables\Columns\TextColumn::make('playback_type')
                    ->label('Playback')
                    ->badge()
                    ->formatStateUsing(fn (?string $state): string => strtoupper((string) ($state ?: 'mp4')))
                    ->color(fn (?string $state): string => $state === 'hls' ? 'success' : 'info')
                    ->toggleable(),
                Tables\Columns\TextColumn::make('hls_worker_status')
                    ->label('HLS Worker')
                    ->badge()
                    ->color(fn (?string $state): string => match ($state) {
                        'queued', 'artifact_ready', 'fetching', 'installing' => 'warning',
                        'completed', 'partial' => 'success',
                        'failed' => 'danger',
                        default => 'gray',
                    })
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('hls_worker_last_error')
                    ->label('Worker Error')
                    ->limit(40)
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('optimize_status')
                    ->label('Optimize')
                    ->badge()
                    ->formatStateUsing(fn (?string $state): string => strtoupper((string) ($state ?: 'pending')))
                    ->color(fn (?string $state): string => match ($state) {
                        'ready' => 'success',
                        'failed' => 'danger',
                        'processing', 'pending' => 'warning',
                        default => 'gray',
                    })
                    ->description(fn (MediaSource $record): ?string => $record->optimize_status === 'failed' && $record->optimize_error ? $record->optimize_error : null)
                    ->toggleable(),
                Tables\Columns\TextColumn::make('file_size_bytes')
                    ->label('Size')
                    ->formatStateUsing(fn (?int $state): string => $state ? $this->formatBytes($state) : '-'),
                Tables\Columns\TextColumn::make('progress_percent')
                    ->label('Progress')
                    ->formatStateUsing(fn (?int $state): string => (($state ?? 0) . '%'))
                    ->description(function (MediaSource $record): string {
                        $downloaded = $record->bytes_downloaded ? $this->formatBytes((int) $record->bytes_downloaded) : '0 B';
                        $total = $record->bytes_total ? $this->formatBytes((int) $record->bytes_total) : 'Unknown';
                        return "{$downloaded} / {$total}";
                    })
                    ->badge()
                    ->color(fn (MediaSource $record): string => match ($record->status) {
                        'ready' => 'success',
                        'failed' => 'danger',
                        default => 'warning',
                    }),
                Tables\Columns\TextColumn::make('public_url')
                    ->label('Public URL')
                    ->state(fn (MediaSource $record) => app(MediaSourceService::class)->buildPublicUrl($record))
                    ->copyable()
                    ->toggleable(),
                Tables\Columns\TextColumn::make('hls_master_url')
                    ->label('HLS Master URL')
                    ->state(function (MediaSource $record): ?string {
                        $playback = app(MediaSourceService::class)->buildPlaybackManifest($record);
                        return isset($playback['hls_master_url']) ? (string) $playback['hls_master_url'] : null;
                    })
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('mp4_play_url')
                    ->label('MP4 Playback URL')
                    ->state(function (MediaSource $record): ?string {
                        $playback = app(MediaSourceService::class)->buildPlaybackManifest($record);
                        return isset($playback['mp4_play_url']) ? (string) $playback['mp4_play_url'] : null;
                    })
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('download_url')
                    ->label('Download URL')
                    ->state(function (MediaSource $record): ?string {
                        $playback = app(MediaSourceService::class)->buildPlaybackManifest($record);
                        return isset($playback['download_url']) ? (string) $playback['download_url'] : null;
                    })
                    ->copyable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->since(),
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make()
                    ->label('Import Source')
                    ->using(function (array $data): MediaSource {
                        $asset = $this->getOwnerRecord();
                        $service = app(MediaSourceService::class);

                        $sourceType = $data['source_type'];
                        $importedSourceId = isset($data['imported_source_id']) ? (int) $data['imported_source_id'] : null;
                        $importMode = (string) ($data['import_mode'] ?? config('cdn.default_import_mode', 'queue'));

                        if ($sourceType === 'remote_fetch' && $importedSourceId) {
                            $existing = MediaSource::where('id', $importedSourceId)
                                ->where('media_asset_id', $asset->id)
                                ->first();

                            if ($existing) {
                                $existing->update([
                                    'source_url' => $data['source_url'] ?? $existing->source_url,
                                    'is_active' => (bool) ($data['is_active'] ?? $existing->is_active),
                                ]);

                                return $existing->fresh();
                            }
                        }

                        if ($sourceType === 'upload') {
                            $source = $service->attachStoredUpload($asset, (string) $data['upload_file']);
                            Notification::make()
                                ->success()
                                ->title('Upload import started')
                                ->body('Local upload was attached and processed.')
                                ->send();
                            return $source;
                        }

                        $source = MediaSource::create([
                            'media_asset_id' => $asset->id,
                            'source_type' => $sourceType,
                            'source_url' => $data['source_url'] ?? null,
                            'status' => in_array($sourceType, ['url', 'embed'], true) ? 'ready' : 'pending',
                            'is_active' => (bool) ($data['is_active'] ?? true),
                        ]);

                        if ($sourceType === 'remote_fetch') {
                            if ($importMode === 'now') {
                                $service->importRemoteNow($source);
                                $source->refresh();
                            } else {
                                $service->queueRemoteImport($source);
                            }
                            if ($importMode === 'now') {
                                if ($source->status === 'failed') {
                                    Notification::make()
                                        ->danger()
                                        ->title('Remote import failed')
                                        ->body($source->failure_reason ?: 'Remote import failed.')
                                        ->send();
                                } else {
                                    Notification::make()
                                        ->success()
                                        ->title('Remote import completed')
                                        ->body('Real-time import completed successfully.')
                                        ->send();
                                }
                            } else {
                                Notification::make()
                                    ->info()
                                    ->title('Remote import queued')
                                    ->body('Use the progress column to monitor download and processing.')
                                    ->send();
                            }
                        } else {
                            $service->refreshAssetStatus($asset);
                        }

                        return $source->fresh();
                    }),
            ])
            ->actions([
                Tables\Actions\Action::make('copy_urls')
                    ->label('Copy URLs')
                    ->icon('heroicon-o-clipboard-document')
                    ->visible(fn (MediaSource $record): bool => $record->status === 'ready')
                    ->fillForm(function (MediaSource $record): array {
                        $service = app(MediaSourceService::class);
                        $playback = $service->buildPlaybackManifest($record);

                        return [
                            'copy_hls_master_url' => (string) ($playback['hls_master_url'] ?? ''),
                            'copy_mp4_play_url' => (string) (($playback['mp4_play_url'] ?? $playback['mp4_url'] ?? '') ?: ''),
                            'copy_download_url' => (string) ($playback['download_url'] ?? ''),
                        ];
                    })
                    ->form([
                        Forms\Components\TextInput::make('copy_hls_master_url')
                            ->label('HLS Master URL')
                            ->readOnly()
                            ->suffixAction(
                                Forms\Components\Actions\Action::make('copy_hls_master_url_btn')
                                    ->icon('heroicon-o-clipboard-document')
                                    ->action(fn (Forms\Get $get) => Notification::make()->success()->title('Copied HLS URL')->body((string) $get('copy_hls_master_url'))->send())
                            ),
                        Forms\Components\TextInput::make('copy_mp4_play_url')
                            ->label('MP4 Playback URL')
                            ->readOnly(),
                        Forms\Components\TextInput::make('copy_download_url')
                            ->label('Download URL (Original MP4)')
                            ->readOnly(),
                    ])
                    ->modalSubmitAction(false),
                Tables\Actions\EditAction::make()
                    ->mutateRecordDataUsing(function (array $data): array {
                        $data['upload_file'] = null;
                        return $data;
                    })
                    ->using(function (MediaSource $record, array $data): MediaSource {
                        $service = app(MediaSourceService::class);
                        $sourceType = $data['source_type'] ?? $record->source_type;
                        $importMode = (string) ($data['import_mode'] ?? config('cdn.default_import_mode', 'queue'));

                        if ($sourceType === 'upload' && ! empty($data['upload_file'])) {
                            return $service->replaceStoredUpload($record, (string) $data['upload_file']);
                        }

                        $record->update([
                            'source_type' => $sourceType,
                            'source_url' => $data['source_url'] ?? null,
                            'is_active' => (bool) ($data['is_active'] ?? $record->is_active),
                        ]);

                        if ($sourceType === 'remote_fetch' && ! empty($record->source_url)) {
                            if ($importMode === 'now') {
                                $service->importRemoteNow($record);
                            } else {
                                $service->queueRemoteImport($record);
                            }
                        } else {
                            $service->refreshAssetStatus($record->asset);
                        }

                        return $record->fresh();
                    })
                    ->after(function (): void {
                        app(MediaSourceService::class)->refreshAssetStatus($this->getOwnerRecord());
                    }),
                Tables\Actions\Action::make('refresh_status')
                    ->label('Refresh')
                    ->icon('heroicon-o-arrow-path')
                    ->action(function (MediaSource $record): void {
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        Notification::make()
                            ->success()
                            ->title('Status refreshed')
                            ->send();
                    }),
                Tables\Actions\Action::make('retry_import')
                    ->label('Retry import now')
                    ->icon('heroicon-o-arrow-path')
                    ->visible(fn (MediaSource $record): bool => $record->source_type === 'remote_fetch')
                    ->requiresConfirmation()
                    ->action(function (MediaSource $record): void {
                        app(MediaSourceService::class)->importRemoteNow($record);
                        $record->refresh();
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        if ($record->status === 'failed') {
                            Notification::make()
                                ->danger()
                                ->title('Import retry failed')
                                ->body($record->failure_reason ?: 'Remote import failed.')
                                ->send();
                        } else {
                            Notification::make()
                                ->success()
                                ->title('Import retry completed')
                                ->body('Remote source imported successfully.')
                                ->send();
                        }
                    }),
                Tables\Actions\Action::make('queue_optimization')
                    ->label('Queue for optimization')
                    ->icon('heroicon-o-arrow-right-on-rectangle')
                    ->color('info')
                    ->visible(fn (MediaSource $record): bool => $record->status === 'ready' && in_array($record->optimize_status, ['pending', 'failed'], true))
                    ->action(function (MediaSource $record): void {
                        app(MediaSourceService::class)->queuePlaybackProcessing($record);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        Notification::make()
                            ->success()
                            ->title('Queued for optimization')
                            ->body('Source has been sent to the worker (or local queue). Optimize status will update when processing completes.')
                            ->send();
                    }),
                Tables\Actions\Action::make('run_reoptimise')
                    ->label('Run re-optimise')
                    ->icon('heroicon-o-cpu-chip')
                    ->color('info')
                    ->visible(fn (MediaSource $record): bool => $record->status === 'ready')
                    ->requiresConfirmation()
                    ->modalHeading('Re-optimise this source')
                    ->modalDescription('Re-run MP4 faststart and HLS generation for this source. The job will be queued and may take several minutes.')
                    ->action(function (MediaSource $record): void {
                        app(MediaSourceService::class)->queuePlaybackProcessing($record);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                        Notification::make()
                            ->success()
                            ->title('Re-optimise queued')
                            ->body('Optimization (MP4 faststart + HLS) has been queued. Progress will update in the table.')
                            ->send();
                    }),
                Tables\Actions\Action::make('disable_source')
                    ->label('Disable source')
                    ->color('warning')
                    ->icon('heroicon-o-no-symbol')
                    ->visible(fn (MediaSource $record): bool => $record->is_active)
                    ->action(function (MediaSource $record): void {
                        $record->update(['is_active' => false]);
                        app(MediaSourceService::class)->refreshAssetStatus($record->asset);
                    }),
                Tables\Actions\DeleteAction::make()
                    ->after(fn () => app(MediaSourceService::class)->refreshAssetStatus($this->getOwnerRecord())),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\BulkAction::make('queue_optimization_bulk')
                        ->label('Queue selected for optimization')
                        ->icon('heroicon-o-arrow-right-on-rectangle')
                        ->color('info')
                        ->requiresConfirmation()
                        ->modalHeading('Queue for optimization')
                        ->modalDescription('Send selected ready sources to the worker (or local queue) for faststart + HLS. Only sources with status Ready and optimize_status Pending/Failed will be queued.')
                        ->action(function (\Illuminate\Database\Eloquent\Collection $records): void {
                            $service = app(MediaSourceService::class);
                            $queued = 0;
                            foreach ($records as $record) {
                                if ($record->status === 'ready' && in_array($record->optimize_status, ['pending', 'failed'], true)) {
                                    $service->queuePlaybackProcessing($record);
                                    $queued++;
                                }
                            }
                            $service->refreshAssetStatus($this->getOwnerRecord());
                            Notification::make()
                                ->success()
                                ->title('Queued for optimization')
                                ->body($queued > 0 ? "{$queued} source(s) queued." : 'No eligible sources (only ready sources with Pending/Failed optimize status are queued).')
                                ->send();
                        }),
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    private function formatBytes(int $bytes): string
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];
        $size = $bytes;
        $unit = 0;

        while ($size >= 1024 && $unit < count($units) - 1) {
            $size /= 1024;
            $unit++;
        }

        return round($size, 2) . ' ' . $units[$unit];
    }
}

